export const menu_data = {
    'Master' : ["Bank","Bank Info","Employee"],
    'Vehicle Valuation' : ["New Intimation","Schedule","Mis","Inspection Done","Create Report","Modify Report","Final Report","Modify After Final"],
    'Property Valuation' : ["New Intimation","Schedule","Mis","Inspection Done","Create Report","Modify Report","Final Report","Modify After Final"],
    'Billing' : ["Vechile","Propery","MIS","Modify"],
    'Report' : ['Create Report','Report Format','Generate Report']
}

export const form_data = 
{
"Master":{

    'Bank' : [{title: 'Bank Name', type: 'text'},{title: 'Personal Email', type: 'email'}, {title: 'Phone Number', type: 'number',} ],
    'Bank Info' : [
        {title: 'Bank Name', type: ['datadropdown',['Bank Name','Master/Bank']]},
        {title: 'Bank Phon Number', type: "autofill", "parentField" : ["Bank Name", "Master/Bank","Phone Number","Bank Name"]},
        {title: 'Branch', type: 'text'},
        {title: 'IFSC Code', type: 'text'},
        {title :"Bank Address", type: "text"},
        {title :"Bank Division", type: "text"},
        {title :"Bank Contact Person Name", type: "text"},
        {title :"Bank Contact Person Number", type: "text"},
        {title :"Bank Contact Person Email Id", type: "text"},
        {title :"Bank Manager Name", type: "text"},
        {title :"Bank Manager Number", type: "number"},
        {title :"Bank Manager Email Id", type: "email"},
        {title :"Extra Remark", type: "text"},
    ],
    'Employee' : [
        {title : "Empolyee Name", type : "text"},
        {title : "Mobile Number", type : "number"},
        {title: 'Email Id', type: 'email'},
        {title : "Address", type : "text"},
        {title : "Aadhar Number", type : "number"},
        {title : "Pan Number", type : "number"},
        {title : "Image", type : "image"},
        {title : "Password", type : "password"},
    ]
},
'Vehicle Valuation':{
            'New Intimation' : [
                {title: 'Ref. No.', type: 'text'},
                {title: 'Company Name', type: ["datadropdown",["Bank Name","Master/Bank"]]},
                {title: 'Bank Division', type: "autofill", "parentField" : ["Company Name", "Master/Bank Info","Bank Division","Bank Name"]},
                {title: 'Bank Branch', type: "autofill", "parentField" : ["Company Name", "Master/Bank Info","Branch","Bank Name"]},
                // {title :"Bank Branch", type: "text"},
                // {title :"Vertical", type: "autofill", "parentField" : ["Company Name", "Master/Bank","Personal Email","Bank Name"]},
                {title :"Vertical", type: "text"},
                {title :"Intimated By", type: "autofill", "parentField" : ["Company Name", "Master/Bank Info","Bank Contact Person Name","Bank Name"]},
                {title :"Intimation Contact Number", type: ["dropdown",["data","datatat"]]},
                {title :"Intimation Contact Date", type: "date"},
                {title :"Intimation Time", type: "time"},
                {title :"Prospect No.", type: "number"},
                {title :"USED/REPO", type: ["dropdown",["USED", "REPO"]]},
                {title :"Vehicle Type", type: ["dropdown",["CAR", "COMMERCIAL", "EQUIPMENT", "PLANT", "TRACTOR"]]},
                {title :"Customer Name", type: "text"},
                {title :"Customer Number", type: "text"},
                {title :"Vehicle No.", type: "text"},
                {title :"Make/Model", type: "text"},
                {title :"Location of Vehicle", type: "text"},
                {title :"Inspected By", type: ["datadropdown",["Empolyee Name","Master/Employee"]]},
                {title :"Inspector Contact No", type: "autofill", "parentField" : ["Inspected By", "Master/Employee","Mobile Number","Empolyee Name"]},
                {title :"Base Location", type: "text"},
                {title :"Date and Time of Inspection", type: "text"}
    ],
    'Mis' : [
        {title: 'Ref. No.', type: 'number'},
        {title: 'Company Name', type: 'text'},
        {title: 'Bank Division', type: 'text'},
        {title :"Bank Branch", type: "text"},
        {title :"Vertical", type: "text"},
        {title :"Intimated By", type: ["dropdown",["data","datatat"]]},
        {title :"Intimation Contact Number", type: ["dropdown",["data","datatat"]]},
        {title :"Intimation Contact Date", type: "date"},
        {title :"Intimation Time", type: "time"},
        {title :"Prospect No.", type: "number"},
        {title :"USED/REPO", type: ["dropdown",["USED", "REPO"]]},
        {title :"Vehicle Type", type: ["dropdown",["CAR", "COMMERCIAL", "EQUIPMENT", "PLANT", "TRACTOR"]]},
        {title :"Customer Name", type: "text"},
        {title :"Customer Number", type: "text"},
        {title :"Vehicle No.", type: "text"},
        {title :"Make/Model", type: "text"},
        {title :"Location of Vehicle", type: "text"},
        {title :"Inspected By", type: "text"},
        {title :"Inspector Contact No.", type: "text"},
        {title :"Base Location", type: "text"},
        {title :"Date and Time of Inspection", type: "text"}
    ],
    'Schedule':[
        {title :"Intimation Date", type: "date"},
        {title :"Intimation Time", type: "time"}
    ],
},"Property Valuation":{
    'New Intimation':[
        {title: 'Ref No.', type: 'text'},
        {title :"Status", type: "text"},
        {title :"Request Date", type: "text"},
        {title :"Request Time", type: "time"},
        {title :"Bank/ Fin Co. Name", type: "text"},
        {title :"Division", type: "text"},
        {title :"Branch", type: "text"},
        {title :"Vertical", type: "text"},
        {title :"Valuation Type", type: "text"},
        {title :"Login ID / File NO.", type: "text"},
        {title :"Customer Name", type: "text"},
        {title :"Contact No.", type: "text"},
        {title :"Property Address", type: "text"},
        {title :"Main Location", type: "text"},
        {title :"Name of SM/Agent", type: "text"},
        {title :"Contact No of Agent / SM", type: "text"},
    ],
    "Mis":[
        {title: 'Ref No.', type: 'text'},
        {title :"Status", type: "text"},
        {title :"Request Date", type: "date"},
        {title :"Request Time", type: "time"},
        {title :"Bank/ Fin Co. Name", type: "text"},
        {title :"Division", type: "text"},
        {title :"Branch", type: "text"},
        {title :"Vertical", type: "text"},
        {title :"Valuation Type", type: "text"},
        {title :"Login ID / File NO.", type: "text"},
        {title :"Customer Name", type: "text"},
        {title :"Contact No.", type: "text"},
        {title :"Property Address", type: "text"},
        {title :"Main Location", type: "text"},
        {title :"Name of SM/Agent", type: "text"},
        {title :"Contact No of Agent / SM", type: "text"},
        {title :"Remarks", type: "text"},
        {title :"Value Name", type: "text"},
        {title :"Location of Valuer", type: "text"},
        {title :"Date of Alottment", type: "text"},
        {title :"Time of Alottment", type: "time"},
        {title :"Inspection Date", type: "date"},
        {title :"Inspection Time", type: "time"},
        {title :"KM", type: "text"},
        {title :"Remarks by Inspector", type: "text"},
        {title :"Report No.", type: "text"},
        {title :"Report Date", type: "date"},
        {title :"Value Amount", type: "text"},
        {title :"Report Delivery Date", type: "text"},
        {title :"Date of Uploaded / Mailed", type: "date"},
        {title :"Bill Status", type: "text"},
        {title :"Fee Charge", type: "text"},
        {title :"Conv.", type: "text"},
        {title :"Pay Status", type: "text"},
        {title :"Pay Amount", type: "text"},
        {title :"Pay Date", type: "text"},
        {title :"Billing Date", type: "text"}
    ],
    "Inspection Done":[
        {title: 'Ref No.', type: 'text'},
        {title :"Status", type: "text"},
        {title :"Request Date", type: "date"},
        {title :"Request Time", type: "time"},
        {title :"Bank/ Fin Co. Name", type: "text"},
        {title :"Division", type: "text"},
        {title :"Branch", type: "text"},
        {title :"Vertical", type: "text"},
        {title :"Valuation Type", type: "text"},
        {title :"Login ID / File NO.", type: "text"},
        {title :"Customer Name", type: "text"},
        {title :"Contact No.", type: "text"},
        {title :"Property Address", type: "text"},
        {title :"Main Location", type: "text"},
        {title :"Name of SM/Agent", type: "text"},
        {title :"Contact No of Agent / SM", type: "text"},
        {title :"Inspection Date", type: "date"},
        {title :"Inspection Time", type: "time"},
        {title :"KM", type: "text"},
        {title :"Remarks by Inspector", type: "text"}
    ]
}
}
